### ISSUE TITLE
T-frogの組み立て

### ISSUE THREAD

**Issue by ItoYusuke** [open-rdc/autonomous-vehicle#1]
T-frogを組み立てて動作検証する

**Comment by DaikiMaekawa** [comment]
#3 #2 でデバイスドライバの動作を確認中

**Comment by DaikiMaekawa** [comment]
メカ自体の組み立ては終了

**Comment by DaikiMaekawa** [comment]
3年生で二体目のt-flogの組み立てを行う予定

**Comment by DaikiMaekawa** [comment]
@open-rdc/tsukuba-challenge 二体目の組み立ては完了しましたか?
進捗は6/24日に確認します。

**Comment by ShotaroTerato** [comment]
7/1にt-flogの組み立てを開始しましたが、部品表に記載されているがない部品（モータードライバー基板・サーキットプロテクタ・ねじ-タップ-M3-16）、また部品表に記載されていないが必要になる部品（ねじ-M3-5・基板用スペーサ）があります。

**Comment by ShotaroTerato** [comment]
モータードライバ基板は確保。
サーキットプロテクタは後日届く予定。
ネジ類・スペーサは購入する必要あり。

**Comment by yasuohayashibara** [comment]
サーキットプロテクタに関しては，納品されたようです．

**Comment by DaikiMaekawa** [comment]
@ShotaroTerato ネジ類・スペーサに関しては必要個数分の購入をお願いします。
7月20日までにお願いします。

**Comment by yasuohayashibara** [comment]
前回は追加部品無しで製作できたような気がします．６月５日にメーリングリストに流した見積書に今回購入した部品のリストがありますので，確認していただければと思います．

**Comment by ShotaroTerato** [comment]
確認しましたところ、見積もり書に記載されている部品はサーキットプロテクタ以外すべてありました。
ネジに関しては、１台目のT-frogの余りのものを使用すれば足りると思われます。

**Comment by ShotaroTerato** [comment]
組み立て説明を見る限り、回路を本体に取り付けるときに、部品表・見積書には書かれていない部品でM5用のスプリングワッシャが必要になるのですが、ありません。購入する必要があるようです。

１台目のT-frogでは、同じ部分にスプリングワッシャは使用されておらず、回路も固定されていませんでしたが、それと同じように組み立ててしまってよろしいのでしょうか？

**Comment by yasuohayashibara** [comment]
スプリングワッシャはあったほうが良いです．工作センタにあるかもしれません．（確かねじ類はいくつか常備していると話していたような気がします．）なければホームセンタで購入してください．

**Comment by ShotaroTerato** [comment]
スプリングワッシャを２台分購入しました。

**Comment by ShotaroTerato** [comment]
T-frog(i-Cart mini)の組み立てが完了しました。

![01b105a0d2d3ae30f127fe1501aa12d9d0cddec942](https://cloud.githubusercontent.com/assets/7301081/3554339/e2bd76c6-090b-11e4-8d4f-e4914cdbc4bc.jpg)

**Comment by kk3104** [comment]
組み終わったのでクローズします
