### ISSUE TITLE
メガローバの電源ケーブルの断線

### ISSUE THREAD

**Issue by DaikiMaekawa** [open-rdc/autonomous-vehicle#10]
クリスマスツリーを動かそうとしたのですが，焦げた匂いがして，動きませんでした．見ると電源ケーブルが断線しておりました．故障の紙を貼って線を切っておいておきましたが，修理をお願いします．
ケーブルが無線アダプタの金属部分に接触していたようですので，その部分が壊れているおそれがあります．

**Comment by DaikiMaekawa** [comment]
コネクタを修理すれば修復できそうです。

**Comment by Nasupl** [comment]
コネクタの修理ですが、完了しています。
しかしながら、コントローラからの信号の受信感度が非常に弱く、まともに応答してくれません。
コントローラ側の電池はあるので、受信モジュールの問題ではないかと考えていますが、はっきりとはわかりませんので、一度受信モジュールを新品に交換して問題の切り分けをしたいです。
@yasuohayashibara  新品の受信モジュールの場所を教えてください。

**Comment by yasuohayashibara** [comment]
新品の受信モジュールですが，１８Fの林原の机周辺にあります．今度部屋にいるときに声をかけて下さい．

**Comment by Nasupl** [comment]
新品のモジュールに交換したところ、問題なく動作するようになりました。
古いモジュールと新品モジュールに外見上の際はほぼ見られませんが、受信感度が圧倒的に弱いので、どこかが短絡の影響を受けてダメになったのだと思われます。
古いモジュールはMegaRoverの上のピンクの静電防止エアパッキンにいれてあります。

**Comment by yasuohayashibara** [comment]
交換お疲れさまです．間違って使用することを防ぐため，故障したと思われる受信機に関しては破棄しましょう．

**Comment by DaikiMaekawa** [comment]
@Nasupl 故障したモジュールを破棄したらこのタスクを閉じて下さい。

**Comment by Nasupl** [comment]
破棄しました
