### ISSUE TITLE
MegaRoverのバッテリー過放電とDCDCコンバータ故障。

### ISSUE THREAD

**Issue by Nasupl** [open-rdc/autonomous-vehicle#11]
先ほど、ミーティング後の開発時間に @iou16 より、MegaRover1.1が動かないとの報告を受けましたので、バッテリー電圧を確認すると、4V近くまで放電し、過放電の状態に至っておりました。
その後、バッテリーの充電を開始しましたが、その際に充電の極性を誤ったため、バッテリーの極性を反転させてしまいました。
最終的に、極性が反転した状態で電源を投入してしまったため、URGやサーボに電源を供給しているDC-DCコンバータ（ZUS-25-1212）を破損してしまいました。
MegaRover基板や、URG、サーボ等、DC-DCコンバータ以外の部品が正常に動作することは確認済みです。
バッテリーは現在、正しい極性で再度充電して回復を実施しています。

@yasuohayashibara お忙しいところ申し訳ありませんが、DC-DCコンバータ[（ZUS-25-1212）](https://www.cosel.co.jp/jp/products/sub05-4.html)の調達をよろしくお願いします。

**Comment by yasuohayashibara** [comment]
RSコンポーネンツにDC-DCコンバータを発注しました．バッテリも交換したほうが良いと思います．あと，今回の失敗を繰り返さないためにも，ケーブルを逆にさせないようにコネクタを作り替えたほうが良いと思います．

**Comment by Nasupl** [comment]
DC-DCコンバータの換装はすでに実施しました。
バッテリの交換はまだ実施していませんが、MegaRover1.0に搭載されているバッテリーの電圧を測定したところ、12V近い電圧が出ていましたので、こちらとの積み替えで対応可能だと思います。バッテリーの積み替えについては、以降 #12 のIssueに引き継いで実施できればと考えています。
コネクタの構造変更についてですが、こちらについては、 #6 にて実施中のタスクになりますので、以降そちらに引き継いで報告します。

**Comment by Nasupl** [comment]
こちらのイシューも残タスクないので閉じます。
