### ISSUE TITLE
メガローバの整備

### ISSUE THREAD

**Issue by DaikiMaekawa** [open-rdc/autonomous-vehicle#12]
- 無くなったネジの補充(緩んで落ちた)
- マジックテープの交換

**Comment by DaikiMaekawa** [comment]
@iou16 井上君よろしくお願いします。

**Comment by Nasupl** [comment]
#11 に書きましたが、MegaRover1.0からのバッテリーの積み替えもお願いします。

**Comment by Nasupl** [comment]
バッテリの積み替え、ネジの交換を確認しました。
#6 にて、バッテリのコネクタの違いについての報告がありましたので、こちらについてもMegaRover1.1用バッテリについていたケーブルを今回積み替えたバッテリに付け替えることで対応しました。

**Comment by iou16** [comment]
バッテリの積み替え、無くなったネジの補完及び、マジックテープの交換は全て完了しました。

**Comment by DaikiMaekawa** [comment]
@iou16 他に問題等なければこのタスクを閉じて下さい。
