### ISSUE TITLE
OpenCV：traincascadeによるhaartraining

### ISSUE THREAD

**Issue by ShotaroTerato** [open-rdc/autonomous-vehicle#13]
OpenCVでhaartrainingユーティリティを使用し分類器の訓練をしようとしたところ、以下のようなエラーが発生してしまう。
![opencv_test3](https://cloud.githubusercontent.com/assets/7301081/4212747/ae6a24f0-38a4-11e4-9e65-0aacbe8c7fea.png)

ディレクトリ構成:OpenCV2.4.9
 vc12/bin/ 
       　　　opencv_haartraining.exe 
       　　　nonfacejpg/
       　　　　　　　B1_00001.jpg
       　　　　　　　B1_00002.jpg
                           ~
                        B1_00039.jpg
                        B1_00040.jpg
       　　　　　　　bg.txt 
       　　　rawdata/
       　　　　　　　cmu_0000.jpg
                        cmu_0001.jpg
                            ~
                        cmu_0470.jpg
                        cmu_0471.jpg
       　　　　　　　vec/
       　　　　　　　　　　facejpg.vec
       　　　data/
       　　　　　　　cascade/

**Comment by ShotaroTerato** [comment]
invalid background description file

背景記述ファイル（bg.txt）が良くないというエラー

bg.txtは以下の通り
nonfacejpg\B1_00001.jpg
nonfacejpg\B1_00002.jpg
nonfacejpg\B1_00003.jpg
nonfacejpg\B1_00004.jpg
nonfacejpg\B1_00005.jpg
nonfacejpg\B1_00006.jpg
nonfacejpg\B1_00007.jpg
nonfacejpg\B1_00008.jpg
nonfacejpg\B1_00009.jpg
nonfacejpg\B1_00010.jpg
nonfacejpg\B1_00011.jpg
nonfacejpg\B1_00012.jpg
nonfacejpg\B1_00013.jpg
nonfacejpg\B1_00014.jpg
nonfacejpg\B1_00015.jpg
nonfacejpg\B1_00016.jpg
nonfacejpg\B1_00017.jpg
nonfacejpg\B1_00018.jpg
nonfacejpg\B1_00019.jpg
nonfacejpg\B1_00020.jpg
nonfacejpg\B1_00021.jpg
nonfacejpg\B1_00022.jpg
nonfacejpg\B1_00023.jpg
nonfacejpg\B1_00024.jpg
nonfacejpg\B1_00025.jpg
nonfacejpg\B1_00026.jpg
nonfacejpg\B1_00027.jpg
nonfacejpg\B1_00028.jpg
nonfacejpg\B1_00029.jpg
nonfacejpg\B1_00030.jpg
nonfacejpg\B1_00031.jpg
nonfacejpg\B1_00032.jpg
nonfacejpg\B1_00033.jpg
nonfacejpg\B1_00034.jpg
nonfacejpg\B1_00035.jpg
nonfacejpg\B1_00036.jpg
nonfacejpg\B1_00037.jpg
nonfacejpg\B1_00038.jpg
nonfacejpg\B1_00039.jpg
nonfacejpg\B1_00040.jpg

\を/に変更したり、改行コードCR+LFを各行に足して実行したが、同じエラーが出てしまう。

**Comment by Nasupl** [comment]
.\nofacejpg\B1_*.jpgみたいな感じにしてもダメでしょうか

**Comment by ShotaroTerato** [comment]
.\nonfacejpg\B1__.jpg または ./nonfacejpg/B1__.jpg　のようにして試行してみましたが、上記とまったく同じエラーになってしまいました。

**Comment by ShotaroTerato** [comment]
./nonfacejpg/B1_*jpgのように記述し、bg.txtをopencv/build/x86/vc12/bin直下に配置することによって、上記のエラーが出なくなりました。
学習が終了するまで時間がかかり、この先エラーが起こらないとも限らないので、しばらくはこのissueは開けておきたいと思います。
![4](https://cloud.githubusercontent.com/assets/7301081/4283088/4aa27bc0-3d68-11e4-9e93-8eda44ff2e3b.png)

**Comment by ShotaroTerato** [comment]
エラーは出ないが、14段階あるノードのうち3段階目のノードの時に下の画像の画面のまま進まなくなり、
5時間ほど放置したが何の変化も見て取れなくなってしまう。
![5](https://cloud.githubusercontent.com/assets/7301081/4345206/2f75d484-40bd-11e4-9914-2e0a65313cee.png)

**Comment by ShotaroTerato** [comment]
opencv_haartrainingはサポートが廃止されているとのことなので、今後はopencv_traincascadeを使用しhaartrainingを行う。
![7](https://cloud.githubusercontent.com/assets/7301081/4347171/13860e2a-4139-11e4-80db-47a01c82e481.png)

**Comment by ShotaroTerato** [comment]
opencv_traincascadeでも同様に3階層目で進まなくなるが、メモリがオーバーフローしていないので今のところ正常に学習が行われていると思われる。
学習には10時間単位の時間がかかるようなので待つ必要がある。

![8](https://cloud.githubusercontent.com/assets/7301081/4347178/e9412662-4139-11e4-9fe0-a1399a9b6371.png)
![6](https://cloud.githubusercontent.com/assets/7301081/4347176/9ce87432-4139-11e4-9c36-941924883b06.png)

**Comment by ShotaroTerato** [comment]
約24時間経過したが、未だ変化が見られない。
![9](https://cloud.githubusercontent.com/assets/7301081/4351059/b185a5cc-4201-11e4-8751-2b7247748084.png)

**Comment by ShotaroTerato** [comment]
生成したポジティブサンプルデータを確認したところ、背景画像と統合されたポジティブサンプルがうまく
生成されていなかった。これが原因で学習が進まなくなっていると思われる。

![create_sample](https://cloud.githubusercontent.com/assets/7301081/4472178/1e5eaf10-4944-11e4-963b-c0471a88c663.png)
