### ISSUE TITLE
URGがうまくデータを取得できない

### ISSUE THREAD

**Issue by Nasupl** [open-rdc/autonomous-vehicle#15]
本日のプレ試走会で走行させたところ、屋内のランドマークが多い場所で走行させてもうまくデータを取得できず、オドメトリとIMUで走行していました。
#14 でt-frog搭載サーボをMegaRoverに移植した際に、t-frogに搭載されていたサーボが115200bpsで通信するように設定されていたため、規定の460800bpsから変更したのが原因かもしれません。サーボ側の通信速度の設定を変更して、確認する必要があるかと思います。

**Comment by Nasupl** [comment]
Futabaから配布されているMemoryMapEditorでROM領域の読み込み/書き換えを試みましたが、読み込みができませんでした。

**Comment by yasuohayashibara** [comment]
ロボカップで経験値の高い先輩に助けを求めたほうが良いかもしれません．

**Comment by ItoYusuke** [comment]
サーボは指令を受け取って動いていますか？

ROM領域のデータを読み込めない原因は幾つか考えられます．
ボーレート変更時にサーボへの書き換えをおこないましたか？
益子か伊藤が現物と履歴を洗えば対処できるとおもいます．

2014-09-16 20:29 GMT+09:00 Yasuo Hayashibara notifications@github.com:

> ロボカップで経験値の高い先輩に助けを求めたほうが良いかもしれません．
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/open-rdc/autonomous-vehicle/issues/15#issuecomment-55729141
> .

## 

---

千葉工業大学
工学部 未来ロボティクス学科
1126016 伊藤 裕介
Tell ：080-8852-6003
MailAddress ： itoyusuke.mobilemail@gmail.com

**Comment by Nasupl** [comment]
@ItoYusuke 
サーボは指令を受け取って動いています。
サーボのボーレートは私の方では書き換えを行っておらず、Autonから取り外した時点で11500bpsとなっていました。
「460800bpsから115200bpsに変更した」というのは、MegaRoverのソフトウェアでサーボとの通信速度として設定されているボーレートを115200bpsに変更して、サーボ側に合わせたということです。

**Comment by Nasupl** [comment]
ボーレートの問題ではなく、サーボから返ってきたデータのチェックサムの計算がおかしかったため、角度の取得が正常に取得できなかったのが問題でした。
#16 でコードを修正して、問題なく動作するようになったので、このIIssueをクローズします。
