### ISSUE TITLE
電圧計の取り付けを行う

### ISSUE THREAD

**Issue by DaikiMaekawa** [open-rdc/autonomous-vehicle#17]
i-Cart-miniとMegaRoverに電圧計の取り付けを行う

**Comment by Nasupl** [comment]
i-Cart-mini側は外装が固まり次第取り付けを行います。MegaRover側はマジックテープで機体に貼り付ければ完了です。

**Comment by Nasupl** [comment]
MegaRoverは取り付けを行いました

**Comment by DaikiMaekawa** [comment]
@Nasupl i-Cart miniの外装が完成したので、取り付けをお願いします。

**Comment by Nasupl** [comment]
完了しているので閉じます
