### ISSUE TITLE
メガローバのプログラムのエラーについて

### ISSUE THREAD

**Issue by kk3104** [open-rdc/autonomous-vehicle#18]
メガローバを走行させようとしたところ、メガローバとカメラがコネクトされていないとエラーが出ました。
USBハブに繋がっているものが認識されていないようです。

**Comment by DaikiMaekawa** [comment]
@kk3104 OS側からデバイスとして認識されていないということでしょうか?
認識されているならばCOMが変わっているだけかもしれませんよ。

**Comment by kk3104** [comment]
デバイスマネージャーで確認したところusbハブ自体は認識されていましたが、それに繋がっているwebカメラなどの認識はされていないようでした

ポートは前に動いていた状態から変えていないので間違えていないはずです

**Comment by ItoYusuke** [comment]
ハブから全ケーブルを抜いて，１つずつ接続して確認してください．
問題が無ければすべて接続できるはずです．

//ポートは前に動いていた状態から変えていないので間違えていないはずです
固定していなければ起動によってポートは変動しますよ？

2014年10月6日 17:44 kusakabe kazuaki notifications@github.com:

> デバイスマネージャーで確認したところusbハブ自体は認識されていましたが、それに繋がっているwebカメラなどの認識はされていないようでした
> 
> ポートは前に動いていた状態から変えていないので間違えていないはずです
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/open-rdc/autonomous-vehicle/issues/18#issuecomment-57989060
> .

## 

---

千葉工業大学
工学部 未来ロボティクス学科
1126016 伊藤 裕介
Tell ：080-8852-6003
MailAddress ： itoyusuke.mobilemail@gmail.com

**Comment by kk3104** [comment]
ありがとうございます

今は学校に行くことが出来ないので明日の朝試してみます

**Comment by Nasupl** [comment]
ハブを変えると認識するので、ハブがダメかもしれません。

**Comment by kk3104** [comment]
今日、自分が買っておきます

**Comment by kk3104** [comment]
同じ型番のものがなかったので、とりあえず同じメーカーのものを買おうと思います

**Comment by kk3104** [comment]
ハブの取替えが完了しました
動作確認が終わったので閉じます
