### ISSUE TITLE
モータドライバをWindowsで扱う

### ISSUE THREAD

**Issue by ItoYusuke** [open-rdc/autonomous-vehicle#2]
T-frog付属のモータドライバをWindowsで扱えるか検証する

**Comment by DaikiMaekawa** [comment]
@kk3104  5/27のミーティングまでに完了させる。

**Comment by kk3104** [comment]
進捗
・安定化電源よりモータドライバに5Vを供給し、USBでPCと接続したところモータドライバを認識できた

・マニュアルの4.3章を参考にコマンドを入力したところ、以下の画像のように
ERROR : cannot open spur.
とエラーが出た
![zikkoukekka](https://cloud.githubusercontent.com/assets/5432320/3064409/75d68546-e252-11e3-9578-333a8b040444.PNG)

・上記のエラー原因を調査中

**Comment by DaikiMaekawa** [comment]
@kk3104 Spur_init()で初期化に失敗しているようですね。
Spurの導入手順に不備はありませんか?
#3 でLinux上での動作確認はできたようですのでモータドライバの問題ではないと思われます。

**Comment by kk3104** [comment]
手順はマニュアル通りやったのですがもう一度確認してみます

ありがとうございます

**Comment by nao-in** [comment]
使わない方針
