### ISSUE TITLE
Mega Rover ver.1.0 のモータドライバの故障

### ISSUE THREAD

**Issue by yasuohayashibara** [open-rdc/autonomous-vehicle#4]
Mega Rover ver.1.0 のモータドライバの故障中です．
修理が必要であると思います．

**Comment by Nasupl** [comment]
モータドライバ基板のFETが燃えてしまったようです。
メーカーに発注する必要があります。

**Comment by DaikiMaekawa** [comment]
@Nasupl 動かないロボットが出てしまうのは問題なので発注お願いします。

**Comment by DaikiMaekawa** [comment]
@Assignee @Nasupl

**Comment by kk3104** [comment]
修理から戻ってきたので後で組み立てが必要

**Comment by Nasupl** [comment]
天板を取り付けて組み立てが完了しました。
