### ISSUE TITLE
Mega Rover ver.1.1用のチャージャの修理

### ISSUE THREAD

**Issue by yasuohayashibara** [open-rdc/autonomous-vehicle#5]
Mega Rover ver.1.1用のチャージャの修理が必要です．

**Comment by DaikiMaekawa** [comment]
Assignee @Nasupl

**Comment by Nasupl** [comment]
チャージャー（アルインコの安定化電源装置）のメーターが振れない問題のようです。
電源をいれれば12Vは出力されているようですが、それが正しく出力されているのかは不明です。
購入して1年以内のようなので、メーカーに送っての修理が必要になると思われます。

**Comment by DaikiMaekawa** [comment]
保証対象外と言われたため、現在メーカと交渉中

**Comment by DaikiMaekawa** [comment]
メーカは修理しないといっているので、中を空けて様子を確認する。 @Nasupl

**Comment by Nasupl** [comment]
電源の回路図が書いてあるメンテナンスシートをWeb上で発見したので中を開けて導通等をチェックしたのですが、メータ以外に問題がある部分を発見できませんでした。メータ自体の交換が必要そうです。

**Comment by kk3104** [comment]
交換不可なのでクローズします
