### ISSUE TITLE
Mega Rover 1.1の回路系再構築

### ISSUE THREAD

**Issue by Nasupl** [open-rdc/autonomous-vehicle#6]
MegaRover1.1の運用容易化のために、電源投入系を始めとする回路周りの再構成の検討が必要です。（林原先生より）

**Comment by DaikiMaekawa** [comment]
@yasuohayashibara MegaRover1.1は今年の大会に使用しますか?
使用するのであれば担当者を決めて取り組んだ方がよさそうですね。

**Comment by yasuohayashibara** [comment]
どうしましょうか？
私としては，昨年度同様バックアップとして考えているのですが，状況によってはメインで使用するかもしれません．
とりあえず２チームで登録して，準備が整わない内はメガローバでデータを取るというつもりでいます．

**Comment by DaikiMaekawa** [comment]
@yasuohayashibara バックアップとしては貴重な存在なので @Nasupl に回路周りの再構築を検討してもらうことになりました。

**Comment by DaikiMaekawa** [comment]
Milestone : 2014年6月末

**Comment by Nasupl** [comment]
試走会の運用を加味して再度構築を行います

**Comment by DaikiMaekawa** [comment]
9月9日締切り

**Comment by Nasupl** [comment]
#11 のインシデントを基に、基板を製作しました。現在ワイヤハーネスに用いるケーブルが研究室にないので、これを入手し接続すれば完了します。以前の回路からの変更点等については、ワイヤハーネスの製作後に報告します。

**Comment by Nasupl** [comment]
再構築した回路の運用方法について、Wikiに以下のようにまとめました。参照してください。
このタスクは完了したとして一度閉じます。
[電源ケーブル周辺の変更・運用について  ](https://github.com/open-rdc/autonomous-vehicle/wiki/%E9%9B%BB%E6%BA%90%E3%82%B1%E3%83%BC%E3%83%96%E3%83%AB%E5%91%A8%E8%BE%BA%E3%81%AE%E5%A4%89%E6%9B%B4%E3%83%BB%E9%81%8B%E7%94%A8%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6)

**Comment by iou16** [comment]
MegaRover1.0のバッテリーを取り出してみたのですが、やはりMegaRover1.1のバッテリーとコネクタの形状が違いました。
また、ケーブルの長さが足りないと思われます。
