### ISSUE TITLE
アルインコの電源ファン修理

### ISSUE THREAD

**Issue by kk3104** [open-rdc/autonomous-vehicle#7]

**Comment by nao-in** [comment]
予備の電源のファンが故障

**Comment by yasuohayashibara** [comment]
そういえば，２台の電源の異なる部分が壊れているので，２個１にしても良いかもしれません．
計器が壊れているほうがより深刻なような気がしますので，ファンだけ取り外して取り付けるので良いと思います．

**Comment by Nasupl** [comment]
メータ故障個体から、ファン故障個体へ、ファンを移植しました。
しかしながら、ボリュームによる電圧調整ができない状態なので、再度調整が必要です。

**Comment by yasuohayashibara** [comment]
遅くなりましたが，電源の後ろに電圧を固定するスライダスイッチがあります．
ご確認下さい．

**Comment by DaikiMaekawa** [comment]
スライダスイッチを操作しても特に変わりませんでした。
内部的な故障が疑われます。

**Comment by yasuohayashibara** [comment]
なるほどこちらも深刻な故障を抱えていたのですね．修理しようとする人がいない場合は，破棄して下さい．必要に応じて電源を購入しますので，リクエスト下さい．

**Comment by Nasupl** [comment]
@yasuohayashibara  3台あったものが2台壊れてしまっているということで、故障率が高いように感じます。とりあえず1台は残っていますが、こちらもいつ故障してもおかしくないのではと思いますので、ALINCO DM-330MVを1台予備として購入をお願いします。

**Comment by yasuohayashibara** [comment]
購入しました．

**Comment by Nasupl** [comment]
ありがとうございます。このイシューは完了ということで閉じます。

**Comment by yasuohayashibara** [comment]
届きましたので，日下部君の机の上に置いておきました．
