### ISSUE TITLE
持っていく荷物チェック

### ISSUE THREAD

**Issue by Nasupl** [open-rdc/autonomous-vehicle#8]
金曜日に行う荷物チェック等の時間は何時にしますか？

**Comment by kk3104** [comment]
台風が金曜に来るとのことだったので今日準備しちゃいました

**Comment by nao-in** [comment]
日下部君から連絡があったように，台風の影響で金曜日には行えそうになかったので，荷物準備は予め済ませてしまいました．

12日は，7:30に集合し，荷物の積み込みが終わり次第8:00までに出発する予定です．
集合場所は研究室にします．

**Comment by yasuohayashibara** [comment]
メガローバはデータを取得できるようになりました？

**Comment by kk3104** [comment]
URGでデータ取得ができませんでした
サーボも動いていない状態です
デバイスマネージャーで確認したところ認識はしています
webカメラでの映像取得はできています

画像の載せ方がわからなかったのでFacebookにデバイスマネージャーの画像を載せます

**Comment by DaikiMaekawa** [comment]
@kk3104 Issueにドラッグアンドドロップで画像を貼り付けられますよ

**Comment by kk3104** [comment]
デバイスマネージャの画像です
さっきはiPhoneから投稿しようとしていたのが悪かったみたいです
![1](https://cloud.githubusercontent.com/assets/5432320/3534973/1739b4ca-07f7-11e4-9662-422f5a0f5c8f.JPG)

**Comment by Nasupl** [comment]
サーボの不調の件ですが、調査したところ電源供給線が断線していました。
断線については修理を既に完了しています。

**Comment by kk3104** [comment]
サーボの動作確認ができました
同時にURGもデータの取得ができるようになりました

**Comment by yasuohayashibara** [comment]
良かったです．サーボの問題は別のissueにしたほうが良かったかもしれません．持ち物チェックが終了したらクローズしてください．

**Comment by kk3104** [comment]
終わったのでクローズします
