### ISSUE TITLE
ジャイロの調整

### ISSUE THREAD

**Issue by kk3104** [open-rdc/autonomous-vehicle#9]
ジャイロのオフセットの調整が必要です

**Comment by yasuohayashibara** [comment]
ジャイロの値が取得できているかが気になります．
#defineで機能を切れるようにしていますので，データが取得できているかを確認して下さい．
端的に分かるのが，プログラムを動かした状態で，持ち上げて回転させると，もしGyroが機能している場合は，GUIのロボットの向きが変わります．Gyroが機能していない場合は，回転しません．

**Comment by kk3104** [comment]
プログラムを動かした状態でロボットを持ち上げ回転させたところguiに変化はありませんでした

**Comment by kk3104** [comment]
デバイスマネージャーでimuのポートを確認したところUSB Serial Port と出るだけでメーカー名やジャイロセンサなどの表記はなかったのですがこれは最初からでしょうか

**Comment by yasuohayashibara** [comment]
おそらくはIMUの機能がOFFになっていると思われます．
H/Wではなくて，ソフトウェア的に使用しないような設定になっていると思われますので，
#define USE_IMU
がコメントアウトされていないか確認して下さい．

**Comment by kk3104** [comment]
ソースコードを確認したところコメントアウトされていませんでした

何か他の原因だと思うのですがまだ特定できません

**Comment by kk3104** [comment]
今ロボットを台車に載せ、車輪を回さずにロボットの向きを変えた所、画面内のロボットの向きも変わっていたため、imuは動作していました。

今までのusbのセッティングが間違っていた様です。

**Comment by DaikiMaekawa** [comment]
@kk3104 結局、この問題は解決されたということでよろしいのでしょうか？

**Comment by DaikiMaekawa** [comment]
@Nasupl から無事動作したとの報告を受けたためこのIssueを閉じます。
